version: '3.3'
services:
  db:
    image: postgres:11.3
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=app
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5050:5050
    environment:
      - PGADMIN_LISTEN_PORT=5050
      - PGADMIN_DEFAULT_EMAIL=app@mail.com
      - PGADMIN_DEFAULT_PASSWORD=admin123
    depends_on:
      - db
